version: "3.8"

services:
  front:
    container_name: front
    depends_on:
      - mongodb
    #on build le server avec le dockerfile du dossier Front
    build: ./Front
    restart: unless-stopped
    env_file: ./.env
    environment:
      - UID=&UID
      - GUD=&GUD
    ports:
      - $REACT_PORT:$REACT_PORT
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
    networks:
      - front


volumes:
  db:

networks:
  front:
    driver: bridge
